# Generated by Django 5.1.5 on 2025-02-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jfif', null=True, upload_to='profile_pics'),
        ),
    ]
