# Generated by Django 5.1.5 on 2025-02-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
