# Generated by Django 5.1.6 on 2025-03-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_student_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='assets\\img\\default.jpg', upload_to='profile_pics'),
        ),
    ]
