# Generated by Django 5.1.6 on 2025-03-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Grade',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course_id',
            new_name='grade_id',
        ),
    ]
