# Generated by Django 5.1.6 on 2025-03-12 12:37

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_subject_grade_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default=app.models.generate_admission_number, editable=False, max_length=50, unique=True),
        ),
    ]
